export default [
    "Alemania",
    "Argelia",
    "Agentina",
    "Australia",
    "Bélgica",
    "Bonia",
    "Brasil",
    "Camerún",
    "Chile",
    "Colombia",
    "Corea del sur",
    "Costa de Marfíl",
    "Costa Rica",
    "Croacia",
    "Ecuador",
    "España",
    "Estados Unidos",
    "Francia",
    "Ghana",
    "Grecia",
    "Honduras",
    "Inglaterra",
    "Iran",
    "Italia",
    "Japón",
    "México",
    "Nigeria",
    "Paises Bajos",
    "Portugal",
    "Rusia",
    "Suiza",
    "Uruguay"]